package com.loongzee.cms.dao.model;

import java.io.Serializable;

public class CmsArticleTag implements Serializable {
    /**
     * 编号
     *
     * @mbg.generated
     */
    private Integer articleTagId;

    /**
     * 文章编号
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     * 标签编号
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_tag.article_tag_id
     *
     * @return the value of cms_article_tag.article_tag_id
     *
     * @mbg.generated
     */
    public Integer getArticleTagId() {
        return articleTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_tag.article_tag_id
     *
     * @param articleTagId the value for cms_article_tag.article_tag_id
     *
     * @mbg.generated
     */
    public void setArticleTagId(Integer articleTagId) {
        this.articleTagId = articleTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_tag.article_id
     *
     * @return the value of cms_article_tag.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_tag.article_id
     *
     * @param articleId the value for cms_article_tag.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_tag.tag_id
     *
     * @return the value of cms_article_tag.tag_id
     *
     * @mbg.generated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_tag.tag_id
     *
     * @param tagId the value for cms_article_tag.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleTagId=").append(articleTagId);
        sb.append(", articleId=").append(articleId);
        sb.append(", tagId=").append(tagId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CmsArticleTag other = (CmsArticleTag) that;
        return (this.getArticleTagId() == null ? other.getArticleTagId() == null : this.getArticleTagId().equals(other.getArticleTagId()))
            && (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()))
            && (this.getTagId() == null ? other.getTagId() == null : this.getTagId().equals(other.getTagId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getArticleTagId() == null) ? 0 : getArticleTagId().hashCode());
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        result = prime * result + ((getTagId() == null) ? 0 : getTagId().hashCode());
        return result;
    }
}