package com.loongzee.cms.dao.model;

import java.io.Serializable;

public class CmsCategoryTag implements Serializable {
    /**
     * 编号
     *
     * @mbg.generated
     */
    private Integer categoryTagId;

    /**
     * 类目编号
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * 标签编号
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_category_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category_tag.category_tag_id
     *
     * @return the value of cms_category_tag.category_tag_id
     *
     * @mbg.generated
     */
    public Integer getCategoryTagId() {
        return categoryTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category_tag.category_tag_id
     *
     * @param categoryTagId the value for cms_category_tag.category_tag_id
     *
     * @mbg.generated
     */
    public void setCategoryTagId(Integer categoryTagId) {
        this.categoryTagId = categoryTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category_tag.category_id
     *
     * @return the value of cms_category_tag.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category_tag.category_id
     *
     * @param categoryId the value for cms_category_tag.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category_tag.tag_id
     *
     * @return the value of cms_category_tag.tag_id
     *
     * @mbg.generated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category_tag.tag_id
     *
     * @param tagId the value for cms_category_tag.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category_tag
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoryTagId=").append(categoryTagId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", tagId=").append(tagId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category_tag
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CmsCategoryTag other = (CmsCategoryTag) that;
        return (this.getCategoryTagId() == null ? other.getCategoryTagId() == null : this.getCategoryTagId().equals(other.getCategoryTagId()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getTagId() == null ? other.getTagId() == null : this.getTagId().equals(other.getTagId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category_tag
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCategoryTagId() == null) ? 0 : getCategoryTagId().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getTagId() == null) ? 0 : getTagId().hashCode());
        return result;
    }
}