package com.loongzee.cms.dao.model;

import java.io.Serializable;

public class CmsSetting implements Serializable {
    private Integer settingId;

    private String settingKey;

    private String settingValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_setting.setting_id
     *
     * @return the value of cms_setting.setting_id
     *
     * @mbg.generated
     */
    public Integer getSettingId() {
        return settingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_setting.setting_id
     *
     * @param settingId the value for cms_setting.setting_id
     *
     * @mbg.generated
     */
    public void setSettingId(Integer settingId) {
        this.settingId = settingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_setting.setting_key
     *
     * @return the value of cms_setting.setting_key
     *
     * @mbg.generated
     */
    public String getSettingKey() {
        return settingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_setting.setting_key
     *
     * @param settingKey the value for cms_setting.setting_key
     *
     * @mbg.generated
     */
    public void setSettingKey(String settingKey) {
        this.settingKey = settingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_setting.setting_value
     *
     * @return the value of cms_setting.setting_value
     *
     * @mbg.generated
     */
    public String getSettingValue() {
        return settingValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_setting.setting_value
     *
     * @param settingValue the value for cms_setting.setting_value
     *
     * @mbg.generated
     */
    public void setSettingValue(String settingValue) {
        this.settingValue = settingValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", settingId=").append(settingId);
        sb.append(", settingKey=").append(settingKey);
        sb.append(", settingValue=").append(settingValue);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CmsSetting other = (CmsSetting) that;
        return (this.getSettingId() == null ? other.getSettingId() == null : this.getSettingId().equals(other.getSettingId()))
            && (this.getSettingKey() == null ? other.getSettingKey() == null : this.getSettingKey().equals(other.getSettingKey()))
            && (this.getSettingValue() == null ? other.getSettingValue() == null : this.getSettingValue().equals(other.getSettingValue()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSettingId() == null) ? 0 : getSettingId().hashCode());
        result = prime * result + ((getSettingKey() == null) ? 0 : getSettingKey().hashCode());
        result = prime * result + ((getSettingValue() == null) ? 0 : getSettingValue().hashCode());
        return result;
    }
}