package com.loongzee.upms.dao.mapper;

import com.loongzee.upms.dao.model.UpmsLog;
import com.loongzee.upms.dao.model.UpmsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpmsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    long countByExample(UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int deleteByExample(UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int insert(UpmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int insertSelective(UpmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    List<UpmsLog> selectByExampleWithBLOBs(UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    List<UpmsLog> selectByExample(UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    UpmsLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UpmsLog record, @Param("example") UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") UpmsLog record, @Param("example") UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UpmsLog record, @Param("example") UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UpmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(UpmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UpmsLog record);
}