package com.loongzee.upms.dao.mapper;

import com.loongzee.upms.dao.model.UpmsRole;
import com.loongzee.upms.dao.model.UpmsRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpmsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    long countByExample(UpmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    int deleteByExample(UpmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    int insert(UpmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    int insertSelective(UpmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    List<UpmsRole> selectByExample(UpmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    UpmsRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UpmsRole record, @Param("example") UpmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UpmsRole record, @Param("example") UpmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UpmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UpmsRole record);
}