package com.loongzee.cms.dao.mapper;

import com.loongzee.cms.dao.model.CmsArticleTag;
import com.loongzee.cms.dao.model.CmsArticleTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    long countByExample(CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int deleteByExample(CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer articleTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int insert(CmsArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int insertSelective(CmsArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    List<CmsArticleTag> selectByExample(CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    CmsArticleTag selectByPrimaryKey(Integer articleTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmsArticleTag record, @Param("example") CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmsArticleTag record, @Param("example") CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsArticleTag record);
}