package com.loongzee.cms.dao.mapper;

import com.loongzee.cms.dao.model.CmsMenu;
import com.loongzee.cms.dao.model.CmsMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    long countByExample(CmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    int deleteByExample(CmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    int insert(CmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    int insertSelective(CmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    List<CmsMenu> selectByExample(CmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    CmsMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmsMenu record, @Param("example") CmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmsMenu record, @Param("example") CmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsMenu record);
}