package com.loongzee.cms.dao.mapper;

import com.loongzee.cms.dao.model.CmsSetting;
import com.loongzee.cms.dao.model.CmsSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    long countByExample(CmsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    int deleteByExample(CmsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer settingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    int insert(CmsSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    int insertSelective(CmsSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    List<CmsSetting> selectByExample(CmsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    CmsSetting selectByPrimaryKey(Integer settingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmsSetting record, @Param("example") CmsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmsSetting record, @Param("example") CmsSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsSetting record);
}