package com.loongzee.cms.dao.mapper;

import com.loongzee.cms.dao.model.CmsSystem;
import com.loongzee.cms.dao.model.CmsSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    long countByExample(CmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    int deleteByExample(CmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    int insert(CmsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    int insertSelective(CmsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    List<CmsSystem> selectByExample(CmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    CmsSystem selectByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmsSystem record, @Param("example") CmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmsSystem record, @Param("example") CmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsSystem record);
}