package com.loongzee.cms.dao.mapper;

import com.loongzee.cms.dao.model.CmsTag;
import com.loongzee.cms.dao.model.CmsTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    long countByExample(CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    int deleteByExample(CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    int insert(CmsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    int insertSelective(CmsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    List<CmsTag> selectByExample(CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    CmsTag selectByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmsTag record, @Param("example") CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmsTag record, @Param("example") CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsTag record);
}