package com.loongzee.cms.dao.mapper;

import com.loongzee.cms.dao.model.CmsTopic;
import com.loongzee.cms.dao.model.CmsTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    long countByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int deleteByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int insert(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int insertSelective(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    List<CmsTopic> selectByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    CmsTopic selectByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmsTopic record, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmsTopic record, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsTopic record);
}